version: "3.8"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: curso-php-app
    image: fullcyle/php
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - curso-php-network

  nginx:
    image: nginx:latest
    container_name: curso-php-nginx
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - curso-php-network
  
  db:
        build: ././docker/mysql
        container_name: curso-php-db
        restart: always
        tty: true
        ports:
            - "33006:3306"
        volumes:
            - ././docker/dbdata:/var/lib/mysql
            - ././docker/mysql:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_DATABASE=curso_php
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - curso-php-network

networks:
  curso-php-network:
    driver: bridge
